---
- name: Run frontend
  docker_container:
    name: frontend
    image: amelkdr/tp-devops-frontend:latest
    networks:
      - name: app-network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python