spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:usr}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pwd}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
